### ISSUE TITLE
CopyIn leads to "FATAL:  terminating connection because protocol synchronization was lost" on postgres

### ISSUE THREAD

**Issue by udl** [lib/pq#473]
Hi,
and first of all thank you for the great work you put into the library!
I have a problem that I'm not sure if it actually is a problem or not:
My program uses CopyIn to pump some data (several hundred MB in some million entries) into the postgres.
I discovered ```FATAL:  terminating connection because protocol synchronization was lost``` entries in the postgres log. But my program doesn't return any errors at that point. 

Is this transparently handled by the driver? Is it a bug in the driver? Is it a bug in my code?

I'm sorry that I can't come up with a test to reproduce it. I wasn't able to create one so far. Hopefully I can isolate the problem.

Thank you for your input!

**Comment by johto** [comment]
> Is this transparently handled by the driver? Is it a bug in the driver? Is it a bug in my code?

Really hard to say.  It would be great if you could double check that you're doing error handling correctly, but there's still a fair chance that the error is swallowed due to the automatic reconnecting that happens behind the scenes.

> I'm sorry that I can't come up with a test to reproduce it. I wasn't able to create one so far. Hopefully I can isolate the problem

That would be great.

**Comment by udl** [comment]
I can at least show you what i'm doing:

data is coming in via a channel. the entries are structs from a JSON api
```go

for entries := range productChannel {
  txn, err := db.Begin()
  handleErr(err)
  stmt, err := txn.Prepare(pq.CopyIn("<table>", "<some_column>", "<some_other_column>"))
  handleErr(err)
  defer stmt.Close()
  for _, entry := range entries {
    raw := entry.SomeField
    _, err = stmt.Exec("product", raw, "some other string")
    handleErr(err)
  }
  _, err = stmt.Exec()
  handleErr(err)

  updateStmt, errUpdate := txn.Prepare("UPDATE some_other_table SET some_value=$1")
  handleErr(errUpdate)
  defer updateStmt.Close()
  _, errUpdate = updateStmt.Exec(len(entries))
  handleErr(errUpdate)
  errUpdate = txn.Commit()
  handleErr(errUpdate)
}
```
My handleErr function basically panics. So I should realize something's wrong.
```go
func handleErr(err error) {
  if err != nil {
    log.Error(fmt.Sprintf("Caught error %v", err))
    panic(err)
  }
}
```

I'm still learning go so I wouldn't exclude the option that I'm doing something stupid with defer or something...

**Comment by johto** [comment]
> I'm still learning go so I wouldn't exclude the option that I'm doing something stupid with defer or something...

Hmm..  Which Go version are you on?  You're letting the the CopyIn statement outlive the transaction it's associated with, which I believe used to be a problem on older Go versions.  I *think* it was fixed, but I'm not 100% sure.

Does the problem go away if you close `stmt` before committing the transaction?

P.S. I think your code also has a problem where it leaks the transaction if an error occurs, but that's unrelated.

**Comment by johto** [comment]
> You're letting the the CopyIn statement outlive the transaction it's associated with, which I believe used to be a problem on older Go versions.

Also I'd like to point out that you should not ignore errors from Close().  You can defer the close to make sure you're never leaking anything, but in your "everything went fine" code paths you should practically always check the return value of Close().  This applies to file handles and network sockets as well.

**Comment by udl** [comment]
> Hmm.. Which Go version are you on? You're letting the the CopyIn statement outlive the transaction it's associated with, which I believe used to be a problem on older Go versions. I think it was fixed, but I'm not 100% sure.

1.6.2
Ok, I'll fix that regardless the version.

Thank you for the other hints as well!
I'll change that and see if the error still occurs. Hopefully it's just one of those problems. Will keep you posted..

**Comment by udl** [comment]
I've changed the code to explicitly close the statements before the transaction commits and check the errors of Close():

```go
for entries := range productChannel {
  txn, err := db.Begin()
  handleErr(err)
  stmt, err := txn.Prepare(pq.CopyIn("<table>", "<some_column>", "<some_other_column>"))
  handleErr(err)

  for _, entry := range entries {
    raw := entry.SomeField
    _, err = stmt.Exec("product", raw, "some other string")
    handleErr(err)
  }
  _, err = stmt.Exec()
  handleErr(err)

  // NOW EXPLICITLY CLOSING THE STATEMENT
  err = stmt.Close()
  handleErr(err)  

  updateStmt, errUpdate := txn.Prepare("UPDATE some_other_table SET some_value=$1")
  handleErr(errUpdate)

  _, errUpdate = updateStmt.Exec(len(entries))
  handleErr(errUpdate)

  // NOW EXPLICITLY CLOSING THE STATEMENT
  err = updateStmt.Close()
  handleErr(err)

  errUpdate = txn.Commit()
  handleErr(errUpdate)
}

```

Let's see if the error still appears or not 🍀

**Comment by udl** [comment]
Still seeing `FATAL:  terminating connection because protocol synchronization was lost` in postgres log, but no errors in the go code

**Comment by johto** [comment]
> Still seeing FATAL: terminating connection because protocol synchronization was lost in postgres log, but no errors in the go code

Huh.  Any chance you could get a TCP dump of the session?  If the data is confidential it would be enough to see the message types sent and their order.  Wireshark can extract that information, for example.

**Comment by udl** [comment]
I _think_ I found the problem. It was most likely a synchronization error. 
I inserted the items in a goroutine and only waited until the main thread pumped the last item into the channel (which the goroutine consumes). Therefore the goroutine probably got killed when the main thread was done but the goroutine wasn't.
Stupid me... I'll see if the error still occurs, but I don't think it will.

Thank you for your patience and help!
